# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('einc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcRul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyType', models.CharField(max_length=10)),
                ('Rul1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('BDay', models.DateField()),
                ('PasspNumb', models.IntegerField()),
                ('PasspDate', models.DateField()),
                ('DrLicNumb', models.IntegerField()),
                ('DrLicDate', models.DateField()),
                ('DrLicIfVal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InsComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompName', models.CharField(max_length=200)),
                ('CompCont', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('BDay', models.DateField()),
                ('AddressFact', models.CharField(max_length=100)),
                ('AddressRegistr', models.CharField(max_length=100)),
                ('PasspNumb', models.IntegerField()),
                ('PasspDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('BDay', models.DateField()),
                ('AddressFact', models.CharField(max_length=100)),
                ('AddressRegistr', models.CharField(max_length=100)),
                ('PasspNumb', models.IntegerField()),
                ('PasspDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyID', models.IntegerField()),
                ('PolicyType', models.BooleanField()),
                ('Status', models.IntegerField()),
                ('MonSum', models.IntegerField()),
                ('CarName', models.CharField(max_length=20)),
                ('CarDate', models.DateField()),
                ('CarVIN', models.IntegerField()),
                ('CarRegNum', models.CharField(max_length=10)),
                ('CarDocID', models.IntegerField()),
                ('CarDocType', models.CharField(max_length=10)),
                ('CarDocDate', models.DateField()),
                ('CompName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.InsComp')),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Driver')),
                ('Insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Insured')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyID', models.IntegerField()),
                ('PolicyType', models.BooleanField()),
                ('Status', models.CharField(max_length=20)),
                ('MonSum', models.IntegerField()),
                ('HomeName', models.CharField(max_length=20)),
                ('HomeAddr', models.CharField(max_length=20)),
                ('HomeDate', models.DateField()),
                ('HomeType', models.CharField(max_length=10)),
                ('HomeMater', models.CharField(max_length=10)),
                ('CompName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.InsComp')),
                ('Insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Insured')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Usercli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrID', models.IntegerField()),
                ('DriID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='einc.Driver')),
                ('InsID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='einc.Insured')),
                ('OwnID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='einc.Owner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='policyhome',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Usercli'),
        ),
        migrations.AddField(
            model_name='policycar',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.Usercli'),
        ),
        migrations.AddField(
            model_name='order',
            name='PolCar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='einc.PolicyCar'),
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='einc.Usercli'),
        ),
        migrations.AddField(
            model_name='calcrul',
            name='CompID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einc.InsComp'),
        ),
    ]
