PAYPAL_TEST = True
PAYPAL_WPP_USER = "alexbuldyaev-facilitator_api1.gmail.com"
PAYPAL_WPP_PASSWORD = "JPMTWB2JBMAB825J"
PAYPAL_WPP_SIGNATURE = "AMO7hGu8iyICy1ubMDX2-pK1.jSKASDdyR7siFSkHZJxWyj.wrK.XQkO"
SOCIAL_AUTH_VK_OAUTH2_KEY = ''
SOCIAL_AUTH_VK_OAUTH2_SECRET = ''
